package umath

// Code generated by generate/generate.go from const.go.tmpl. DO NOT EDIT.

// According to [1], int and uint are "either 32 or 64 bits".
// We can't use ^uint(0) directly for MaxValue as it would make it a typed
// constant.
//
// [1]: https://golang.org/ref/spec#Numeric_types
const uintSize = 32 << (^uint(0) >> 32 & 1)

// uint limit values.
const (
	MaxValue = 1<<uintSize - 1
	MinValue = 0
)
