package i64math

// Code generated by generate/generate.go from multiple_test.go.tmpl. DO NOT EDIT.

import (
	"fmt"
	"testing"

	"github.com/stretchr/testify/assert"
)

func ExampleRoundToMultiple_even() {
	fmt.Println(RoundToMultiple(4, 2))
	fmt.Println(RoundToMultiple(5, 2))
	fmt.Println(RoundToMultiple(6, 2))

	fmt.Println(RoundToMultiple(-4, 2))
	fmt.Println(RoundToMultiple(-5, 2))
	fmt.Println(RoundToMultiple(-6, 2))
	// Output:
	// 4
	// 6
	// 6
	// -4
	// -6
	// -6

}

func ExampleRoundToMultiple_odd() {
	fmt.Println(RoundToMultiple(6, 3))
	fmt.Println(RoundToMultiple(7, 3))
	fmt.Println(RoundToMultiple(8, 3))
	fmt.Println(RoundToMultiple(9, 3))

	fmt.Println(RoundToMultiple(-6, 3))
	fmt.Println(RoundToMultiple(-7, 3))
	fmt.Println(RoundToMultiple(-8, 3))
	fmt.Println(RoundToMultiple(-9, 3))
	// Output:
	// 6
	// 6
	// 9
	// 9
	// -6
	// -6
	// -9
	// -9

}

func TestRoundToMultiple(t *testing.T) {
	t.Run("ZeroMultiple", func(t *testing.T) {
		assert.Equal(t, int64(6), RoundToMultiple(6, 0))
		assert.Equal(t, int64(7), RoundToMultiple(7, 0))
		assert.Equal(t, int64(8), RoundToMultiple(8, 0))
		assert.Equal(t, int64(9), RoundToMultiple(9, 0))
		assert.Equal(t, int64(-6), RoundToMultiple(-6, 0))
		assert.Equal(t, int64(-7), RoundToMultiple(-7, 0))
		assert.Equal(t, int64(-8), RoundToMultiple(-8, 0))
		assert.Equal(t, int64(-9), RoundToMultiple(-9, 0))
	})
	t.Run("NegativeMultiple", func(t *testing.T) {
		assert.Equal(t, int64(6), RoundToMultiple(6, -3))
		assert.Equal(t, int64(7), RoundToMultiple(7, -3))
		assert.Equal(t, int64(8), RoundToMultiple(8, -3))
		assert.Equal(t, int64(9), RoundToMultiple(9, -3))
		assert.Equal(t, int64(-6), RoundToMultiple(-6, -3))
		assert.Equal(t, int64(-7), RoundToMultiple(-7, -3))
		assert.Equal(t, int64(-8), RoundToMultiple(-8, -3))
		assert.Equal(t, int64(-9), RoundToMultiple(-9, -3))
	})
}

func ExampleFloorToMultiple() {
	fmt.Println(FloorToMultiple(6, 3))
	fmt.Println(FloorToMultiple(7, 3))
	fmt.Println(FloorToMultiple(8, 3))
	fmt.Println(FloorToMultiple(9, 3))

	fmt.Println(FloorToMultiple(-6, 3))
	fmt.Println(FloorToMultiple(-7, 3))
	fmt.Println(FloorToMultiple(-8, 3))
	fmt.Println(FloorToMultiple(-9, 3))
	// Output:
	// 6
	// 6
	// 6
	// 9
	// -6
	// -9
	// -9
	// -9

}

func TestFloorToMultiple(t *testing.T) {
	t.Run("ZeroMultiple", func(t *testing.T) {
		assert.Equal(t, int64(6), FloorToMultiple(6, 0))
		assert.Equal(t, int64(7), FloorToMultiple(7, 0))
		assert.Equal(t, int64(8), FloorToMultiple(8, 0))
		assert.Equal(t, int64(9), FloorToMultiple(9, 0))
		assert.Equal(t, int64(-6), FloorToMultiple(-6, 0))
		assert.Equal(t, int64(-7), FloorToMultiple(-7, 0))
		assert.Equal(t, int64(-8), FloorToMultiple(-8, 0))
		assert.Equal(t, int64(-9), FloorToMultiple(-9, 0))
	})
	t.Run("NegativeMultiple", func(t *testing.T) {
		assert.Equal(t, int64(6), FloorToMultiple(6, -3))
		assert.Equal(t, int64(7), FloorToMultiple(7, -3))
		assert.Equal(t, int64(8), FloorToMultiple(8, -3))
		assert.Equal(t, int64(9), FloorToMultiple(9, -3))
		assert.Equal(t, int64(-6), FloorToMultiple(-6, -3))
		assert.Equal(t, int64(-7), FloorToMultiple(-7, -3))
		assert.Equal(t, int64(-8), FloorToMultiple(-8, -3))
		assert.Equal(t, int64(-9), FloorToMultiple(-9, -3))
	})
}

func ExampleCeilToMultiple() {
	fmt.Println(CeilToMultiple(6, 3))
	fmt.Println(CeilToMultiple(7, 3))
	fmt.Println(CeilToMultiple(8, 3))
	fmt.Println(CeilToMultiple(9, 3))

	fmt.Println(CeilToMultiple(-6, 3))
	fmt.Println(CeilToMultiple(-7, 3))
	fmt.Println(CeilToMultiple(-8, 3))
	fmt.Println(CeilToMultiple(-9, 3))
	// Output:
	// 6
	// 9
	// 9
	// 9
	// -6
	// -6
	// -6
	// -9

}

func TestCeilToMultiple(t *testing.T) {
	t.Run("ZeroMultiple", func(t *testing.T) {
		assert.Equal(t, int64(6), CeilToMultiple(6, 0))
		assert.Equal(t, int64(7), CeilToMultiple(7, 0))
		assert.Equal(t, int64(8), CeilToMultiple(8, 0))
		assert.Equal(t, int64(9), CeilToMultiple(9, 0))
		assert.Equal(t, int64(-6), CeilToMultiple(-6, 0))
		assert.Equal(t, int64(-7), CeilToMultiple(-7, 0))
		assert.Equal(t, int64(-8), CeilToMultiple(-8, 0))
		assert.Equal(t, int64(-9), CeilToMultiple(-9, 0))
	})
	t.Run("NegativeMultiple", func(t *testing.T) {
		assert.Equal(t, int64(6), CeilToMultiple(6, -3))
		assert.Equal(t, int64(7), CeilToMultiple(7, -3))
		assert.Equal(t, int64(8), CeilToMultiple(8, -3))
		assert.Equal(t, int64(9), CeilToMultiple(9, -3))
		assert.Equal(t, int64(-6), CeilToMultiple(-6, -3))
		assert.Equal(t, int64(-7), CeilToMultiple(-7, -3))
		assert.Equal(t, int64(-8), CeilToMultiple(-8, -3))
		assert.Equal(t, int64(-9), CeilToMultiple(-9, -3))
	})
}
