package imath

// Code generated by generate/generate.go from const.go.tmpl. DO NOT EDIT.

// According to [1], int and uint are "either 32 or 64 bits".
//
// [1]: https://golang.org/ref/spec#Numeric_types
const uintSize = 32 << (^uint(0) >> 32 & 1)

// int limit values.
const (
	MaxValue = 1<<(uintSize-1) - 1
	MinValue = -MaxValue - 1
)
